name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Refresh database
        run: bin/dbiputil-refresh
      - name: Commit refreshed database
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated DB refresh" || echo "No changes to commit"
          git push
      - uses: rubygems/release-gem@v1
